#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
"""
Bootstrap input/<arch>/<site>/ocp-settings.yml from the ERA inventory.

Reads the ERA inventory hosts file produced by `make generate` and writes a
pre-populated ocp-settings.yml with node_roles derived from the inventory groups:

  [nodes]   → worker_gpu
  [support] → control_plane
  [storage] → worker_storage  (if present)

The cluster stanza (name, domain, version, VIPs) and credentials paths are
written with clearly marked TODO values for the operator to fill in before
running `make generate-ocp`.

Usage:
    make init-ocp-settings ARCH=2-8-5-200 SITE=kicktires
    python3 scripts/init-ocp-settings.py --arch 2-8-5-200 --site kicktires [--force]
"""

import argparse
import sys
from pathlib import Path

# ERA inventory group → OCP role
GROUP_TO_OCP_ROLE = {
    "nodes":   "worker_gpu",
    "support": "control_plane",
    "storage": "worker_storage",
}


def parse_hosts_file(hosts_path):
    """Parse an Ansible INI-format hosts file and return {group: [hostname, ...]}."""
    groups = {}
    current_group = None

    for raw_line in hosts_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            # Skip :children and :vars meta-sections
            if ":" in section:
                current_group = None
            else:
                current_group = section
                groups.setdefault(current_group, [])
        elif current_group is not None:
            # Take the first token (hostname); ignore inline vars
            hostname = line.split()[0]
            groups[current_group].append(hostname)

    return groups


def build_node_roles(groups):
    """Return {ocp_role: [hostnames]} from ERA inventory groups."""
    role_map = {}
    for group, ocp_role in GROUP_TO_OCP_ROLE.items():
        hosts = groups.get(group, [])
        if hosts:
            role_map[ocp_role] = sorted(hosts)
    return role_map


def format_node_roles_yaml(role_map):
    """Render node_roles block as indented YAML lines."""
    lines = []
    for role, hosts in role_map.items():
        lines.append(f"  {role}:")
        for h in hosts:
            lines.append(f"    - {h}")
    return "\n".join(lines)


def write_settings(out_path, arch, site, node_roles_yaml):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        f"# ocp-settings.yml — generated by: make init-ocp-settings ARCH={arch} SITE={site}\n"
        f"# Fill in every field marked TODO before running: make generate-ocp ARCH={arch} SITE={site}\n"
        f"\n"
        f"cluster:\n"
        f"  name: ocp-{site}            # TODO: set cluster name\n"
        f"  domain: era.example.com     # TODO: set base domain\n"
        f"  version: \"4.17.0\"           # TODO: set OCP version\n"
        f"  api_vip: \"\"                 # TODO: set API VIP  (reserved IP in the cpu/inband subnet)\n"
        f"  ingress_vip: \"\"             # TODO: set Ingress VIP (reserved IP in the cpu/inband subnet)\n"
        f"\n"
        f"pull_secret_path: ~/.era-secrets/pull-secret.json\n"
        f"ssh_key_path: ~/.ssh/id_ed25519.pub\n"
        f"oem: dell                     # TODO: verify OEM  (dell | hpe | lenovo)\n"
        f"\n"
        f"node_roles:\n"
        f"{node_roles_yaml}\n"
        f"\n"
        f"install_disk:\n"
        f"  overrides: {{}}\n"
        f"\n"
        f"day2: {{}}\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--arch",  required=True, help="Architecture (e.g. 2-8-5-200)")
    parser.add_argument("--site",  default="default", help="Site name (default: default)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing ocp-settings.yml")
    args = parser.parse_args()

    hosts_path = Path("output") / args.arch / args.site / "inventory" / "hosts"
    if not hosts_path.is_file():
        sys.exit(
            f"ERROR: ERA inventory not found at {hosts_path}\n"
            f"  Run 'make generate ARCH={args.arch} SITE={args.site}' first."
        )

    out_path = Path("input") / args.arch / args.site / "ocp-settings.yml"
    if out_path.exists() and not args.force:
        sys.exit(
            f"ERROR: {out_path} already exists.\n"
            f"  Use --force (or FORCE=1) to overwrite."
        )

    groups = parse_hosts_file(hosts_path)
    node_roles = build_node_roles(groups)

    if not node_roles:
        sys.exit(
            "ERROR: no OCP-mappable groups found in ERA inventory.\n"
            "  Expected at least one of: [nodes], [support], [storage]."
        )

    node_roles_yaml = format_node_roles_yaml(node_roles)
    write_settings(out_path, args.arch, args.site, node_roles_yaml)

    print(f"\n  Wrote {out_path}")
    print(f"\n  Node roles populated from ERA inventory:")
    for role, hosts in node_roles.items():
        print(f"    {role:16s}: {', '.join(hosts)}")
    print(f"\n  TODO — fill in before running 'make generate-ocp':")
    print(f"    cluster.domain      base domain (e.g. era.example.com)")
    print(f"    cluster.version     OCP version (e.g. 4.17.0)")
    print(f"    cluster.api_vip     reserved IP in the cpu/inband subnet")
    print(f"    cluster.ingress_vip reserved IP in the cpu/inband subnet")
    print(f"    oem                 dell | hpe | lenovo")
    print(f"\n  Credentials (create before running generate-ocp):")
    print(f"    ~/.era-secrets/pull-secret.json  (from cloud.redhat.com)")
    print(f"    ~/.ssh/id_ed25519.pub            (or update ssh_key_path)")
    print()


if __name__ == "__main__":
    main()
